const mockData = {
  currentPeriod: '2022B',
  modules: [
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': 'x',
      '7': 'x',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      prueba: 'https://goo.gl/forms/yUM3gOjGFhvJhXeO2',
      nombre: 'De los Enteros A los racionales',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_privado: 480000,
      area: 'matemáticas',
      codigo: 'ern',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': 'x',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: 'https://goo.gl/forms/Tsc3yqneRpxjcK3t1',
      nombre: 'Lógica, Conjuntos y Sistemas Numéricos',
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'matemáticas',
      precio_privado: 480000,
      codigo: 'lcsn',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': 'x',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: 'https://goo.gl/forms/huPBeP9N9vLcpjJh1',
      nombre: 'Álgebra Fundamental',
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_privado: 480000,
      area: 'matemáticas',
      codigo: 'af',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': 'x',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: 'https://goo.gl/forms/ws3yuOo8ZraunTmC2',
      nombre: 'Geometría Plana y del Espacio',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      area: 'matemáticas',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_privado: 480000,
      precio_univalle: 230000,
      codigo: 'gpe',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': 'x',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: 'https://goo.gl/forms/kPdmfWOXVy2TaKCn1',
      nombre: 'Geometría Analítica y Trigonometría',
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'matemáticas',
      codigo: 'gat',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': 'x',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: 'https://goo.gl/forms/LQXTzEiwxdY0ZWa22',
      nombre: 'Probabilidad y Estadística',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'matemáticas',
      codigo: 'pe',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': 'x',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: 'https://goo.gl/forms/rNkF6gLST0O8hG9U2',
      nombre: 'Funciones, Sucesiones y Límite',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      area: 'matemáticas',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      codigo: 'fsl',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Energía y Movimiento',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'física',
      precio_privado: 480000,
      codigo: 'em',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'AGE: átomo, gases y estequiometría',
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      area: 'química',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_univalle: 230000,
      codigo: 'age',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'ESE: Estequiometría II, Soluciones y Equilibrio',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'química',
      codigo: 'ese',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'BIOQ: Química Orgánica y Bioquímica',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'química',
      precio_univalle: 230000,
      codigo: 'bioq',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Estudio de los seres vivos y sus procesos vitales',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      area: 'biología',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_privado: 480000,
      codigo: 'blg',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Estudio de los seres vivos y sus procesos vitales II',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      area: 'biología',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_univalle: 230000,
      codigo: 'estsertwo',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Lectura Crítica',
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      area: 'lenguaje',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      codigo: 'lecr',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Escritura Creativa',
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'lenguaje',
      precio_privado: 480000,
      precio_univalle: 230000,
      codigo: 'escr',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': '',
      '11': '',
      prueba: '',
      nombre: 'Música, Percusión y Flauta Dulce - Apreciación Musical',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      area: 'música',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_univalle: 230000,
      codigo: 'muper',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': 'x',
      '2': 'x',
      '3': 'x',
      '4': 'x',
      '5': 'x',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      prueba: '',
      nombre: 'Taller infantil de Teatro',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      area: 'artes',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_univalle: 230000,
      codigo: 'tit',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': 'x',
      '7': 'x',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Taller Juvenil de Teatro',
      precio_publico: 230000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_cobertura: 230000,
      disabled: '',
      area: 'artes',
      precio_privado: 480000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      precio_univalle: 230000,
      codigo: 'tjt',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Taller Preparatorio de Danza',
      link_publico:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-publico/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-privado/',
      area: 'artes',
      precio_privado: 480000,
      precio_univalle: 230000,
      codigo: 'tpd',
      egresado: 'x',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/modulos-en-diferentes-areas-para-estudiantes-de-1-a-11-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Actuación ante Cámaras',
      precio_publico: 230000,
      link_publico: '',
      precio_cobertura: 230000,
      disabled: '',
      link_privado: '',
      precio_privado: 480000,
      area: 'artes',
      codigo: 'actaca',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle: '',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Nivelación Académica Semilleros - Semana - Virtual',
      link_publico:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-regular-nas-regular-publico/',
      precio_publico: 500000,
      precio_cobertura: 500000,
      disabled: '',
      area: 'NAS',
      precio_privado: 700000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-regular-nas-regular-privado/',
      codigo: 'nasv',
      precio_univalle: 500000,
      egresado: 'x',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-regular-nas-regular-publico/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Nivelación Académica Semilleros - Semana - Presencial',
      link_publico:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-regular-nas-regular-publico/',
      precio_publico: 660000,
      precio_cobertura: 660000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-regular-nas-regular-privado/',
      area: 'NAS',
      precio_privado: 880000,
      precio_univalle: 660000,
      codigo: 'nasp',
      egresado: 'x',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-regular-nas-regular-publico/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Nivelación Académica Semileros - Sábados - Presencial',
      link_publico:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-intensivo-nas-intensivo-publico/',
      precio_publico: 600000,
      precio_cobertura: 600000,
      disabled: '',
      precio_privado: 800000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-intensivo-privado/',
      area: 'NAS',
      precio_univalle: 600000,
      codigo: 'nasip',
      egresado: 'x',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-intensivo-nas-intensivo-publico/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Nivelación Académica Semileros - Sábados - Virtual',
      precio_publico: 500000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-intensivo-nas-intensivo-publico/',
      precio_cobertura: 500000,
      disabled: '',
      precio_privado: 700000,
      link_privado:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-intensivo-privado/',
      area: 'NAS',
      codigo: 'nasiv',
      precio_univalle: 500000,
      egresado: 'x',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/pre-icfes-nivelacion-academica-semillero-intensivo-nas-intensivo-publico/',
    },
    {
      '1': 'x',
      '2': 'x',
      '3': 'x',
      '4': 'x',
      '5': 'x',
      '6': 'x',
      '7': 'x',
      '8': 'x',
      '9': '',
      '10': '',
      '11': '',
      prueba: '',
      nombre: 'Recreate Con-Ciencia',
      precio_publico: 380000,
      link_publico:
        'https://www.fundacionunivalle.org/producto/recrearte-con-ciencia/',
      precio_cobertura: 380000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/recrearte-con-ciencia/',
      precio_privado: 380000,
      area: 'talleres',
      precio_univalle: 342000,
      codigo: 'rcc',
      egresado: '',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/recrearte-con-ciencia-relacion-univalle/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      prueba: '',
      nombre: 'Semillero en Familia',
      link_publico:
        'https://www.fundacionunivalle.org/producto/semillero-en-familia/',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      link_privado:
        'https://www.fundacionunivalle.org/producto/semillero-en-familia/',
      precio_privado: 480000,
      area: 'talleres',
      codigo: 'sf',
      precio_univalle: 230000,
      egresado: 'x',
      prerrequisitos: '',
      link_univalle:
        'https://www.fundacionunivalle.org/producto/semillero-en-familia/',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': 'x',
      '5': 'x',
      '6': 'x',
      '7': 'x',
      '8': 'x',
      '9': '',
      '10': '',
      '11': '',
      prueba: '',
      nombre: 'Curso de arte y creación',
      link_publico: '',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      link_privado: '',
      area: 'cursos cortos',
      codigo: 'rca',
      precio_univalle: 230000,
      egresado: '',
      prerrequisitos: '',
      link_univalle: '',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Marketing Digital',
      precio_publico: 230000,
      link_publico: '',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      area: 'cursos cortos',
      link_privado: '',
      codigo: 'mkd',
      precio_univalle: 230000,
      egresado: 'x',
      prerrequisitos: '',
      link_univalle: '',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Desarrollo de habilidades TIC',
      link_publico: '',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      link_privado: '',
      precio_privado: 480000,
      area: 'cursos cortos',
      codigo: 'dhtic',
      precio_univalle: 230000,
      egresado: 'x',
      prerrequisitos: '',
      link_univalle: '',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': 'x',
      '9': 'x',
      '10': 'x',
      '11': 'x',
      prueba: '',
      nombre: 'Lectura y Escritura como aptos  creativos',
      precio_publico: 230000,
      link_publico: '',
      precio_cobertura: 230000,
      disabled: '',
      link_privado: '',
      precio_privado: 480000,
      area: 'cursos cortos',
      codigo: 'lecrea',
      precio_univalle: 230000,
      egresado: 'x',
      prerrequisitos: '',
      link_univalle: '',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      prueba: '',
      nombre: 'Pensamiento lógico y matemático',
      link_publico: '',
      precio_publico: 230000,
      precio_cobertura: 230000,
      disabled: '',
      link_privado: '',
      area: 'cursos cortos',
      precio_privado: 480000,
      precio_univalle: 230000,
      codigo: 'penloma',
      egresado: 'x',
      prerrequisitos: '',
      link_univalle: '',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      prueba: '',
      nombre: 'Emprendimiento e innovación',
      precio_publico: 230000,
      link_publico: '',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      area: 'cursos cortos',
      link_privado: '',
      precio_univalle: 230000,
      codigo: 'empin',
      egresado: 'x',
      prerrequisitos: '',
      link_univalle: '',
    },
    {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': 'x',
      prueba: '',
      nombre: 'Estrategia digital',
      precio_publico: 230000,
      link_publico: '',
      precio_cobertura: 230000,
      disabled: '',
      precio_privado: 480000,
      area: 'cursos cortos',
      link_privado: '',
      precio_univalle: 230000,
      codigo: 'edig',
      egresado: 'x',
      prerrequisitos: '',
      link_univalle: '',
    },
  ],
};
export default mockData;
